更新 .github/workflows/docker-image.yml
Signed-off-by: kenyon <kenyon@noreply.localhost>

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,10 +1,11 @@
-name: Docker Image CI
+name: Build Docker images
 
 on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
+  workflow_dispatch:
 
 jobs:
   build:
@@ -18,27 +19,43 @@ jobs:
       - name: Get Version
         id: get_version
         run: |
+          if [ ! -f .github/version ]; then
+            echo "Error: Version file not found!"
+            exit 1
+          fi
           version=$(cat .github/version)
           echo "VERSION=${version}" >> $GITHUB_ENV
           echo "Version: ${version}"
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-      # Build the Docker image
-      - name: Build the Docker image
-        run: docker buildx build . --file Dockerfile --build-arg ANKI_VERSION=${{ env.VERSION }} --tag anki_syncd:v${{ env.VERSION }}
+      # Set up Docker Buildx
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-      # Save the Docker image to a tar file
-      - name: Save Docker image
-        run: docker save -o anki_syncd_${{ env.VERSION }}.tar anki_syncd:v${{ env.VERSION }}
-
-      # Push the Docker image to the registry
-      - name: Push Docker image
-        env:
-          DOCKER_IMAGE: anki_syncd:v${{ env.VERSION }}
-          GITEA_REPO: ${{ secrets.GITEA_SERVICE }}/${{ secrets.GITEA_USER }}/anki_syncd:v${{ env.VERSION }}
+      # Login to Docker registry
+      - name: Login to Docker Registry
         run: |
           docker login -u ${{ secrets.GITEA_USER }} --password ${{ secrets.GITEA_TOKEN }} ${{ secrets.GITEA_SERVICE }}
-          docker tag $DOCKER_IMAGE $GITEA_REPO
-          docker push $GITEA_REPO
+
+      # Build and push the Docker image
+      - name: Build and push Docker image
+        env:
+          GITEA_REPO: ${{ secrets.GITEA_SERVICE }}/${{ secrets.GITEA_USER }}/anki_syncd:v${{ env.VERSION }}
+        run: |
+          docker buildx build \
+            --platform linux/amd64,linux/arm64 \
+            . \
+            --file Dockerfile \
+            --build-arg ANKI_VERSION=${{ env.VERSION }} \
+            --tag $GITEA_REPO \
+            --push
+
+      # Save the Docker image to a tar file (optional)
+      - name: Save Docker image
+        run: |
+          docker pull ${{ secrets.GITEA_SERVICE }}/${{ secrets.GITEA_USER }}/anki_syncd:v${{ env.VERSION }}
+          docker save -o anki_syncd_${{ env.VERSION }}.tar ${{ secrets.GITEA_SERVICE }}/${{ secrets.GITEA_USER }}/anki_syncd:v${{ env.VERSION }}
 
       # Upload the Docker image tar file as an artifact
       - name: Upload Docker image
